smokey_pork_sliders:
  user: test_test
  calories: 1000
  cook_time: <%= 1.hour.to_i %>
  description: 'These mini burgers are absolutely stunning, all smoky from the bacon and paprika and with the sweet and sour hit from the homemade barbeque sauce. People often add too much to their burgers thinking it will enrich the flavor, but let me tell you, when it comes to burgers, less is more. Trust me.'
  number_of_servings: 4
  prep_time: <%= 30.minutes.to_i %>
  recipe_category: 'bbq'
  total_time: <%= (1.hour + 30.minutes).to_i %>
  title: 'Smokey Pork Sliders with Barbecue Sauce'
  images:
    - filepath: 'db/images/smokey_pork_sliders.jpg'
      filename: 'smokey_pork_sliders.jpg'
  labels:
    - pork
    - dinner
    - entertaining
  ingredient_groups:
    - ingredients:
        - '4 strips of rindless smoked bacon, finely chopped'
        - 'Olive oil'
        - '1 shallot, peeled and finely chopped'
        - '1 tsp smoked paprika'
        - '1 pound ground pork'
        - 'sea salt'
        - 'freshly ground black pepper'
    - name: 'For the barbecue sauce'
      ingredients:
        - 'Olive oil'
        - '1 small onion, peeled and finely diced'
        - '2 garlic cloves, finely chopped'
        - 'Sea salt and freshly ground black pepper'
        - '1 Tbsp brown sugar'
        - '1 tsp smoked paprika'
        - '1 Tbsp cider vinegar'
        - '2 tsp Worcestershire sauce'
        - '6 Tbsp tomato ketchup'
    - name: 'To serve'
      ingredients:
        - 'Mini burger buns/bread rolls'
        - 'Baby Boston lettuce leaves, shredded'
        - 'Slices of smoked Cheddar cheese'
        - 'Slices of tomato'
  instructions:
    - 'First make the barbeque sauce. Heat the oil in a frying pan, add the onion and garlic with some salt and pepper and the sugar, and cook for 5 minutes until softened. Add the paprika and stir to combine. Cook for 10-15 minutes until the onion is caramelizing, then add the vinegar and let it cook for a coupole of minuts. Add the Worcestershire sauce and tomato ketchup, mix well, and continue to cook for about 8 minutes until the sauce has reduced to a dropping consistency. Taste and adjust the seasoning as necessary. Remove from the heat and set aside.'
    - 'While the barbecue sauce is reducing, start preparing the burgers. Cook the bacon in an oiled pan for about 5 minutes until almost cooked through. Add the shallot and continue to cook for 5 minutes untul the shallot is tender and the bacon is crisp. Sprinkle in the smoked paprika and mix well. Continue to cook for 1-2 minuts, then remove from the heat, draining off any excess fat on paper towels, and cool.'
    - 'Season the ground pork with salt and pepper and mix well with the cooked shallots and bacon. Shape into balls the size of golf balls and flatten into patties.'
    - 'Heat a large, heavy-bottomed frying pan with a little oil. Season the patties and cook them for 1-2 minutes on each side, basting with the juices until cooked through and colored. Turn off the heat and leave them to rest in the pan. Top each patty with a slice of cheese, allowing it to melt slightly.'
    - 'Assemble your sliders in mini buns, layered with the barbecue sauce, lettuce, and slices of tomato. Any remaining barbecue sauce will keep in the fridge very well. Serve immediately.'
apple_crisp:
  user: test_test
  public: true
  cook_time: <%= (40.minutes).to_i %>
  description: "This is grams apple crisp recipe."
  number_of_servings: 6
  prep_time: <%= 15.minutes %>
  recipe_category: 'dessert'
  total_time: <%= (45.minutes).to_i %>
  title: 'Apple crisp'
  labels:
    - desserts
  ingredient_groups:
    - ingredients:
      - 4 cups peeled and sliced apples
      - 3/4 cups brown sugar
      - 1/2 cup flour
      - 1/2 cup oats
      - 3/4 tsp cinnamon
      - 3/4 tsp nutmeg
      - 1/3 cup soft butter
  instructions:
    - Preheat the oven to 375°F
    - Place apples in a baking pan
    - Mix the rest of the ingredients until they hold together 
    - Scatter mix on top of the apples
    - Cook for 30-40 minutes or until the apples are no longer hard
new_york_style_pizza:
  user: test_test
  public: false
  cook_time: <%= (8.minutes).to_i %>
  description: "This is the best New York style pizza recipe that I've found"
  number_of_servings: 6
  prep_time: <%= (1.hour + 30.minutes).to_i %>
  recipe_category: 'dinner'
  total_time: <%= (1.hour + 38.minutes).to_i %>
  title: 'New York style pizza'
  labels:
    - dinner
  images:
    - filepath: 'db/images/pizza.jpg'
      filename: 'pizza.jpg'
  ingredient_groups:
    - name: 'For the dough'
      ingredients:
        - 2.5 cups (600 ml) warm water
        - 1 tbsp sugar (15 ml) sugar
        - 1 tsp (5 ml) active dry yeast
        - 2 tbsp (30 ml) olive oil
        - 1 tbsp (15 ml) kosher salt
        - 5 cups (600g) bread flour, plus more for working the dough
        - Cornmeal, semolina flour, or coarse-ground whole wheat flour for dusting
    - name: 'For the sauce'
      ingredients:
        - 1 28 oz (828 ml) can crushed tomatoes
        - 2-4 tbsp (30-60 ml) olive oil
        - 1/4 tsp (1g) sugar
        - 1/2 tsp dried oregano
    - name: 'For the cheese'
      ingredients:
        - 1 tbsp (15 ml) grated parmesan or pecorino cheese
        - 7 ounces (200g) whole-milk, low-moisture mozzarella, freshly grated
  instructions:
    - Start the dough by combining the water, sugar and yeast in a large bowl and let sit for a few minutes. If the yeast goes foamy, it's alive and you're good to proceed (if it doesn't, it's dead and you need new yeast). Add the olive oil and salt and 5 cups (600g) of bread flour. Mix until just combined, then start kneading. Add just enough additional flour to keep the dough workable (i.e. not too sticky) and kneed until you can stretch some of the dough into a thin sheet without it tearing. 
    - Divide the dough into four equal balls and put them in four containers (ideally glass) and lightly coat the balls and the interior of their containers with olive oil. Cover, and either rise at room temperature for two hours, or put them in the refrigerator and let them rise for 1-7 days. (I prefer the long, cold rise.)
    - When you want to bake, put a pizza stone or pizza steel into your oven (mine works best on a high rack position but every oven is different) and preheat to your highest possible temperature, ideally convection, for a full hour.
    - For the sauce, simply mix together the ingredients.
    - Liberally dust a pizza peel with cornmeal (or something similar). Take the cold dough out of the fridge and dust it in flour. Stretch to the widest size and shape that will fit on your peel and stone/steel. Top with just enough sauce to lightly coat the surface. Dust the sauce layer with parmesan, then cover with the mozzarella. Transfer the pizza to the stone/steel and bake until the crust is well-browned and the cheese has browned a bit (but, ideally, has not started oozing out an orange grease layer), 6-7 minutes.
chicken_noodle_soup:
  user: test_test
  cook_time: <%= 20.minutes %>
  calories: 162
  description: 'A really quick chicken noodle soup recipe.'
  number_of_servings: 6
  prep_time: <%= 10.minutes %>
  recipe_category: 'bbq'
  total_time: <%= (30.minutes).to_i %>
  title: 'Chicken noodle soup'
  labels:
    - chicken
    - dinner
  ingredient_groups:
    - ingredients:
      - 1 tablespoon butter
      - ½ cup chopped onion
      - ½ cup chopped celery
      - 4 (14.5 ounce) cans chicken broth
      - 1 (14.5 ounce) can vegetable broth
      - ½ pound chopped cooked chicken breast
      - 1 ½ cups egg noodles
      - 1 cup sliced carrots
      - ½ teaspoon dried basil
      - ½ teaspoon dried oregano
      - salt and pepper to taste
  instructions:
    - In a large pot over medium heat, melt butter. Cook onion and celery in butter until just tender, 5 minutes.
    - Pour in chicken and vegetable broths and stir in chicken, noodles, carrots, basil, oregano, salt and pepper.
    - Bring to a boil, then reduce heat and simmer 20 minutes before serving.


