import { library, dom } from '@fortawesome/fontawesome-svg-core';

import {
    faUtensils,
    faSearch,
    faPlus,
    faCloudUploadAlt,
    faHome,
    faBook,
    faThumbsUp,
    faThumbsDown,
    faTimesCircle,
    faSave,
    faUserCircle,
    faUser,
    faSignOutAlt,
    faSignInAlt,
    faUserPlus,
    faCaretUp,
    faCaretDown,
    faChevronDown,
    faChevronUp,
    faSlidersH,
    faTrash,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faUtensils,
    faSearch,
    faPlus,
    faCloudUploadAlt,
    faHome,
    faBook,
    faThumbsUp,
    faThumbsDown,
    faTimesCircle,
    faSave,
    faUserCircle,
    faUser,
    faSignOutAlt,
    faSignInAlt,
    faUserPlus,
    faCaretUp,
    faCaretDown,
    faChevronDown,
    faChevronUp,
    faSlidersH,
    faTrash,
);

dom.watch();
